services:
  postgres:
    image: postgres:16
    restart: on-failure
    container_name: hdm-social-network-api
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/hdm_internship_social/data
    ports:
      - '5432:5432'

volumes:
  postgres:
